spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ApolloConfigDB?characterEncoding=utf8
    username: root
    password: tiger
server:
  port: 8001
dev_meta: http://localhost:8080/
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8000/eureka/