server:
  port: 8999

spring:
  application:
    name: gateway-app
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          # 默认会将请求路径上的服务名配置为大写
          lower-case-service-id: true
      routes:
        - id: header_route
          uri: lb://user-consumer
          predicates:
            - Header=Authorization, \w+
          #            - Path=/user-consumer/**
          filters:
            - RequestParam=true
#            - AddResponseHeader=filterHeader, headVal

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8000/eureka/

logging:
  level:
    org.springframework.cloud.gateway: debug
