
spring:
  application:
    name: user-service
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8000/eureka/

---
spring:
  profiles: user1
server:
  port: 8101
---
spring:
  profiles: user2
server:
  port: 8102
