server:
  port: 8201

spring:
  application:
    name: user-consumer
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8000/eureka
# feign fallback需使用feign.hystrix.enabled,不要错用hystrix.metrics.enabled
feign:
  hystrix:
    enabled: true